<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<b><?php if ($this->vehicle) :?>
<form action="<?php echo $this->baseUrl ?>/vehicle/delete" method="post">
<p>Are you sure that you want to delete this row
</p>
<div>
    <input type="hidden" name="id" 
        value="<?php echo $this->vehicle->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find vehicle.</p>
<?php endif;?></b>
<?php echo $this->render('footer.phtml'); ?>