<form action="<?php echo $this->baseUrl ?>/register/register<?php echo $this->action; ?>" method="post">
	<h1>Create user</h1>
	<table>
		<tr>
			<td><?=$this->form->name?></td>
		</tr>
		<tr>
			<td><?=$this->form->email?></td>
		</tr>
		<tr>
			<td><?=$this->form->pass?></td>
		</tr>
		<tr>
			<td><?=$this->form->captchaImage?></td>
		</tr>
		<tr>
			<td><?=$this->form->Create?></td>
		</tr>
	</table>
</form>

