<?php echo $this->render('header.phtml'); ?>
<h3><?php echo $this->escape($this->title); ?></h3>
<table border=1>
<tr>
<th>ID</th>
<th>Name</th>
<th>E-Mail</th>
<th>Permission</th>
<th>Activation status</th>

<th> </th>
</tr>
<?php foreach($this->users as $user) : 
$permission = $this->escape($user->permission);
	if ($permission >0){
		$permission_link="Delete permission";
	}
	else {
		$permission_link="Add permission";
	}
?>
<tr>
<td><?php echo $this->escape($user->id);?></td>
<td><?php echo $this->escape($user->name);?></td>
<td><?php echo $this->escape($user->email);?></td>
<td><?php echo $this->escape($user->permission);?></td>
<td><?php echo $this->escape($user->activated);?></td>

<td>
<a href="<?php echo $this->baseUrl; ?>/users/changepermission/id/<?php echo $user->id;?>"><?php echo $permission_link;?></a>
<a href="<?php echo $this->baseUrl; ?>/users/delete/id/<?php echo $user->id;?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->escape($this->baseUrl);?>
<?php echo $this->render('footer.phtml'); ?>